apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  namespace: sales-system

spec:
  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: sales-api

    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

