apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales-api

  template:
    metadata:
      labels:
        app: sales-api


    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: sales-api
          image: sales-image

          ports:
            - containerPort: 3000
              name: sales-api
            - containerPort: 3010
              name: sales-api-debug

          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu


---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    app: sales-api


