apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales-api

  template:
    metadata:
      labels:
        app: sales-api


    spec:
      terminationGracePeriodSeconds: 60

      containers:
        - name: sales-api
          image: sales-image