apiVersion: v1
kind: Namespace
metadata:
  name: sales-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    matchLabels:
      app: sales-api

  template:
    metadata:
      labels:
        app: sales-api


    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: init-migrate-seed
        image: sales-image
        command: ['./sales-admin']
      
      containers:
        - name: sales-api
          image: sales-image

          ports:
            - containerPort: 3000
              name: sales-api
            - containerPort: 3010
              name: sales-api-debug

          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2

          env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          - name: KUBERNETES_NAMESPACE    
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName


---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  namespace: sales-system

spec:
  selector:
    app: sales-api


