apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: sales-system
data:
  tempo.yaml: |-
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
        wal:
          path: /tmp/tempo/wal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: sales-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.7.0
          args:
            - "-config.file=/etc/tempo.yaml"
          ports:
            - containerPort: 3200
            - containerPort: 4317
          volumeMounts:
            - name: config-volume
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
      volumes:
        - name: config-volume
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo-service
  namespace: sales-system
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: grpc-otlp
      port: 4317
      targetPort: 4317
